### ISSUE TITLE
241204 피드백 반영

### ISSUE THREAD

**Issue by 2hanbyeol1** [2hanbyeol1/searchright-blog#2]
> [24.12.04 테스트](https://searchright.net/blog/HR-%EC%B1%84%EC%9A%A9-%EC%A0%84%EB%9E%B5%EC%9D%98-%EB%89%B4%EB%85%B8%EB%A9%80-%EB%8B%A4%EC%9D%B4%EB%A0%89%ED%8A%B8-%EC%86%8C%EC%8B%B1/) 후 피드백 반영

### TODO
- [x] 맨 처음에 나오는 `h2`, `figure` 등에 의해 생기는 **`br` 태그들 삭제**
- [x] 일부 callout에 **style 속성 사라지지 않는 버그**
- [x] **coderabbit ai 연결**
